bind_addr = ":8080"
log_level = "debug"

[store]
database_url = "postgres://restapi:12345@localhost:5432/restapi_dev?sslmode=disable"
# postgres://username:password@host:5432/restapi_dev?sslmode=disable
# "host=localhost port=5432 user=postgres dbname=restapi_dev sslmode=disable"